# Generated by Django 3.2.8 on 2021-10-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0002_photosize_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True, verbose_name='caption'),
        ),
    ]
